export interface AtelierProduct {
  id: string;
  slug: string;
  titleUz: string;
  titleRu: string;
  titleEn: string;
  article: string;
  categorySlug: string;
  categoryName: string;
  material: string;
  dimensions: string;
  warranty: string;
  stockStatus: "IN_STOCK" | "MADE_TO_ORDER";
  descUz: string;
  descRu: string;
  descEn: string;
  images: string[];
  colors?: { name: string; hex: string }[];
  characteristics?: { label: string; value: string }[];
}

export const ATELIER_PRODUCTS: AtelierProduct[] = [
  {
    id: "soprano",
    slug: "soprano-divan",
    titleUz: "Soprano Divan",
    titleRu: "Диван Soprano",
    titleEn: "Soprano Sofa",
    article: "PM-104",
    categorySlug: "living-room",
    categoryName: "Yashash xonasi",
    material: "Bouclé",
    dimensions: "280 × 160 × 78 sm",
    warranty: "3 yil rasmiy kafolat",
    stockStatus: "IN_STOCK",
    descUz: "Bouclé mato, erkin qayrilma shakl, eman ichki tayanch va oliy darajadagi anatomik qulaylik.",
    descRu: "Ткань букле, свободная изогнутая форма, внутренний каркас из массива дуба.",
    descEn: "Bouclé upholstery, sculptural silhouette, solid oak internal frame, ergonomic comfort.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDOofZYvEkNu4UfgDMaosUy9UmOtP7k2S9Vy5nEbKmnpGY6t5SvuO30ek1x_KM6p02iHrHE2XpCM9zXo8VUsUa6Kr4EWa24WbAYYxVq-O2Sj-syvesBg9ChGDVBf9LKeYS1Aw5N-0k0yAWza-80smu7b0UGE2XNCC1FHe30kE1Lu6zqzMzwaJ14NJWkwF1SMFKbAP59nizBsEDWlm0P6fnwJAHCO8mEYNTYtBpfLBQGLqu5PKCk5OLov2y-18jgkGqcOgFu_jxPv-w",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuATnyonbIkv8ZAc6afuYQB25mX2C4CMBJi0udEuFwc9BOZo357mX1Teegjh1r1vN2VyR8U9DzS0gWXZXr9g8YDpshD1c0agf5QT1QnECZ1ytSryK7fZJ8Pj8L4_bSFWNK5iTEhxUZ7wOKXIGiGHzgUYq4-OjiRPIZrfouy7DvgiZm-jKl7s26_fFc1h32vRbVtMgLEoGOcXYKAnDV3juGl5RyBIySeKRG9YslIE4p7xETuhfkf-WCYLSArkvMX-tHO8Lm8xwrXqtNQ",
    ],
    colors: [
      { name: "Krem Bouclé", hex: "#EAE5DF" },
      { name: "Och Kulrang", hex: "#D6D3CD" },
      { name: "Qumrang", hex: "#C7B9A5" },
    ],
    characteristics: [
      { label: "Karkas materiali", value: "Quritilgan tabiiy eman massivi" },
      { label: "Qoplama matosi", value: "Italiya Bouclé (anti-stain)" },
      { label: "To'ldiruvchi", value: "Yuqori zichlikdagi HR poliuretan ko'pik" },
      { label: "Ishlab chiqarish", value: "Toshkent atelyesi, 14 kun" },
    ],
  },
  {
    id: "zen",
    slug: "zen-kreslo",
    titleUz: "Zen Kreslo",
    titleRu: "Кресло Zen",
    titleEn: "Zen Armchair",
    article: "PM-208",
    categorySlug: "living-room",
    categoryName: "Yashash xonasi",
    material: "Tabiiy zig'ir",
    dimensions: "82 × 90 × 76 sm",
    warranty: "3 yil rasmiy kafolat",
    stockStatus: "IN_STOCK",
    descUz: "Tabiiy zig'ir mato, massiv eman karkas, ergonomik vazminlik va yapon minimalizmi ruhiyati.",
    descRu: "Натуральный лен, каркас из массива дуба, эргономичное спокойствие и минимализм.",
    descEn: "Natural linen, solid oak structural silhouette, ergonomic balance and understated craft.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDUsA1mIZqmJE4fL8KmvglBnNAyCfIZX8ZEynm0_c6nCZw6Q1oI9DzdzLwzHrE_QqfQbb7IilOqdutUplShhaTRgqmL1ORzdpHgzarhjzwXewMnXXPW9-kk1n6RneQRRu3D5xvjRtrKJmcgpD_-DOjMeRT0l0yf5mxQ6Mm1KstyqGIBsOugGFTuHgjRJIFS87SUFdYLY08JtuCgj_Y-722-uoT-xVJGNrEWuqHsOVFrBr2AkKNRHXt8Qy528A1Cwm-Fyw9a1mxoiww",
      "https://images.unsplash.com/photo-1580481077195-c3a821a58875?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Tabiiy zig'ir", hex: "#DFD9CD" },
      { name: "Terrakotta", hex: "#A44C27" },
      { name: "To'q ko'mir", hex: "#2A2928" },
    ],
    characteristics: [
      { label: "Karkas materiali", value: "Yaxlit qattiq eman" },
      { label: "Mato tarkibi", value: "100% tabiiy zig'ir va paxta" },
      { label: "Maksimal yuklama", value: "160 kg gacha" },
      { label: "Ishlab chiqarish", value: "Toshkent atelyesi" },
    ],
  },
  {
    id: "aura",
    slug: "aura-tumba",
    titleUz: "Aura Tumba",
    titleRu: "Тумба Aura",
    titleEn: "Aura Nightstand",
    article: "PM-312",
    categorySlug: "bedroom",
    categoryName: "Yotoqxona",
    material: "Tabiiy eman",
    dimensions: "68 × 42 × 60 sm",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "MADE_TO_ORDER",
    descUz: "Eman daraxti, bronza tutqichlar, silliqlangan bo'g'inlar va mayin ochiluvchi tortmalar.",
    descRu: "Цельный дуб, бронзовая фурнитура, шлифованные стыки и бесшумные направляющие.",
    descEn: "Solid oak joinery, aged bronze hardware, honed corners and soft-close mechanism.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuD80viJJMS9eNVA29O-MjcPGcPNf2mpSvNXgmi_7QxgdP8zE2PvaYtcuywm7UKX40txexp08ITgCRQ4CefEEJ6wYlBfo0JhLBJ31id3QhcJKI80dC96oio3oRgOdPFvf6Jxa2y-osqBEQZs1Ivrhbxw4y3SFZ03knrO5Rc6LCZw1jzubySme2yTmCnDLKeDNECMvbhQjAtG0ZMhdIhdQ4FDI_dbK6PNFyD0Hf6ppe_JnYzBsFjbyQvTkWf4Jdo35dRUGchgNWQoL1I",
      "https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Och eman", hex: "#D2B896" },
      { name: "Qoramtir eman", hex: "#4A3B32" },
    ],
    characteristics: [
      { label: "Material", value: "Tanlangan eman massivi" },
      { label: "Furnitura", value: "Avstriya Blum Soft-Close" },
      { label: "Qoplama", value: "Tabiiy ekologik moy va mum" },
    ],
  },
  {
    id: "elegance",
    slug: "elegance-jurnal-stoli",
    titleUz: "Elegance Jurnal Stoli",
    titleRu: "Журнальный столик Elegance",
    titleEn: "Elegance Coffee Table",
    article: "PM-405",
    categorySlug: "living-room",
    categoryName: "Yashash xonasi",
    material: "Travertin",
    dimensions: "120 × 70 × 38 sm",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "IN_STOCK",
    descUz: "Yaxlit eman daraxti va sayqallangan Italiya travertin toshining benuqson hamohangligi.",
    descRu: "Безупречная гармония массива дуба и натурального итальянского травертина.",
    descEn: "Fluted solid oak base paired with hand-finished Italian Roman travertine stone slab.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDMFtGGQr6vtPjqLv8mQQVUr1xG4OuaWJdfh8DCGRWHwdHFBdoa3eg61eEskNVBZ9sBb07cgkLgAQimgZXAGyWLM40nxla466HCC15401hOUDjeLWTOxlPGWRhcjYuclpOX2jmb6ch38U1gtgVC7j5zngJ2xTuNn8rFvP4RhaFku35M4sdwx3DguXV3p3zTwUVMQD0ocnBRWaT0KyD2iz5hTEnHIZoPbiQNz9cQV52lz7-wh7R7DCnfCgQjC8syKlI01fdW2gHc28I",
      "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Klassik travertin", hex: "#E3DAC9" },
      { name: "Nocce tosh", hex: "#B8A38F" },
    ],
    characteristics: [
      { label: "Stol usti", value: "Tabiiy Italiya travertin toshi, 20mm" },
      { label: "Oyoqlar", value: "Massiv frezalangan eman ustunlari" },
      { label: "Kafolat", value: "5 yil tosh va karkasga" },
    ],
  },
  {
    id: "milano",
    slug: "milano-modul-divani",
    titleUz: "Milano Modul Divani",
    titleRu: "Модульный диван Milano",
    titleEn: "Milano Modular Sofa",
    article: "PM-014",
    categorySlug: "living-room",
    categoryName: "Yashash xonasi",
    material: "Bouclé",
    dimensions: "320 × 170 × 74 sm",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "IN_STOCK",
    descUz: "Modulli kompozitsiya, qattiq eman sinch, chuqur ergonomik o'rindiq va premium italyan matosi.",
    descRu: "Модульная композиция, прочный каркас из дуба, глубокая эргономичная посадка.",
    descEn: "Modular sectional composition, kiln-dried oak frame, deep comfort lounging profile.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDKQBUc1Qvq3owuFtCJkj1GvHVzQLI1R6ClMCCtUMoV-4KzQoL-DQhiPQa-YqS7L0pHMsVDVm_mLngIn2Jx5aQJU99IfOBADnptL3fgEI9Wh_G66xrzyGaCyPzjO_S7bD2FyGcA7LqVy56fZAVwnvCGBgRgRKFnXC_XMj018sP_YIAjhueefNpk42aOeO2W200gJCTFLx-e8Irb-YxPr5UZMr547znwrLuWge_m0OTFkBVLB3TLtI3orDwxAJPvT95fjLgnmYIcsys",
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Fil suyagi", hex: "#F3EDE2" },
      { name: "Issiq sienna", hex: "#9E5638" },
      { name: "Zaytun yashil", hex: "#606853" },
    ],
    characteristics: [
      { label: "Modullar soni", value: "3 ta alohida ko'chiriluvchi modul" },
      { label: "Karkas", value: "Yaxlit buk va eman birikmasi" },
      { label: "Kafolat", value: "5 yil" },
    ],
  },
  {
    id: "kyoto",
    slug: "kyoto-yotoqxona-krovati",
    titleUz: "Kyoto Yotoqxona Krovati",
    titleRu: "Кровать Kyoto",
    titleEn: "Kyoto Platform Bed",
    article: "PM-021",
    categorySlug: "bedroom",
    categoryName: "Yotoqxona",
    material: "Yong'oq",
    dimensions: "200 × 220 × 42 sm (Matras: 180×200)",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "MADE_TO_ORDER",
    descUz: "Mat yong'oq yog'ochi, tabiiy zig'ir qoplamali yumshoq boshqotirma va sokin past platforma.",
    descRu: "Массив ореха, изголовье с обивкой из льна и низкая парящая японская платформа.",
    descEn: "American walnut solid wood, tactile linen headboard, low architectural platform.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuD7ZTqapzC3o3cxB8SAD7oOhR5f15J_HsN9n430VY5R1oJS_QI0gCThkJI-erHj4AIJpoAueJIrJUMT2Ac4s4Gjv4Ihs3RsqphSyg8rg2o4A_S-_MEozgMRT1DZRMRezAX0hldS7jhmpgkvSGDdpxRJ51_C1HU2a9qHHBcmir13GuyT_pguQlwckj1Oa9sui6QHubKGLzfZauJ8YWuK6m4Lv7rXYdM-7CB_qJcsHV8-YahFoi2JgIIgP27Oh3NuFvLrZeNRAiKM-o0",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Amerika yong'og'i", hex: "#5C4033" },
      { name: "Och tabiiy eman", hex: "#C8AD7F" },
    ],
    characteristics: [
      { label: "Asos turi", value: "Ortopedik yog'och lamel paneli" },
      { label: "Matras o'lchami", value: "180 × 200 sm standart" },
      { label: "Karkas materiali", value: "Tanlangan tabiiy yong'oq massivi" },
    ],
  },
  {
    id: "verona",
    slug: "verona-konsol",
    titleUz: "Verona Konsol",
    titleRu: "Консоль Verona",
    titleEn: "Verona Console Table",
    article: "PM-008",
    categorySlug: "living-room",
    categoryName: "Yashash xonasi",
    material: "Travertin",
    dimensions: "140 × 40 × 85 sm",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "IN_STOCK",
    descUz: "Italiya tabiiy travertini va qoraytirilgan to'q eman yog'ochining haykaltaroshlik nafosati.",
    descRu: "Итальянский траверин и темный дуб в скульптурном архитектурном исполнении.",
    descEn: "Sculptural Italian travertine plinth with blackened solid oak architectural accents.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuACgs2cK5dXj2eKmdVTnLdXpSXT94NeVTyO7Qt_adjpo41KmnLNXKZekAlIeThGV8YoCHP-MPn2Fs4bOTTpbAKnjaF0Fx7xdGJNudCNonaxdGSROth4rQrZ0xbZoqrA3UnDVHuY6dZUU_Ow_EZAzCc1X3r-3-J9FR72e4htdg9ROjydDvY5bDiC3Li4-YhVPh8gHm0lVD1WX_FIYnhsU0aUhuVSgJpnFChDa019SrLi-N_oRfNFCZIRn2uizlFvkfIbyIUKWlz83Dk",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Travertin & To'q eman", hex: "#C4B29E" },
    ],
    characteristics: [
      { label: "Material", value: "Honed Traverine + Solid Blackened Oak" },
      { label: "Og'irligi", value: "48 kg" },
      { label: "Kafolat", value: "5 yil" },
    ],
  },
  {
    id: "nordic",
    slug: "nordic-kitob-javoni",
    titleUz: "Nordic Kitob Javoni",
    titleRu: "Книжный стеллаж Nordic",
    titleEn: "Nordic Bookcase",
    article: "PM-033",
    categorySlug: "office",
    categoryName: "Ish xonasi",
    material: "Tabiiy eman",
    dimensions: "240 × 36 × 240 sm",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "MADE_TO_ORDER",
    descUz: "Ochiq javonlar, qo'lda sayqallangan eman va metall mixsiz yashirin an'anaviy birikmalar.",
    descRu: "Открытые полки, полированный дуб ручной работы и скрытые традиционные соединения.",
    descEn: "Open shelving grid, hand-rubbed Danish oil finish, seamless traditional joinery.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAwheKyKByXlbB46-k5MvdGHUzn_RNM2K94ph9eyHdrUSkJ35zPaEoNOung75UY6HdDV92r-q16rgvEnnhJ8iO-pNQLkjzsllSyna7QTaULDiRlIOGsyYctPKYQe4Paj6jxZz_2GxWkqFqIsTs_0XhyzGt6NIYsQbPP6ZQY2YwHLLjkUbGGFQ8o8AyYXoMfMLuyeFBbR-HFY3R5tbud4z9hogRrJRPX5J1Fy5jILjP-FfLW_mNfK7B-q9xOR5y7452tXgFuaDd10UQ",
      "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Tabiiy eman", hex: "#D5BA93" },
      { name: "Tutunli eman", hex: "#6E5B4B" },
    ],
    characteristics: [
      { label: "Yog'och", value: "100% Yaxlit eman massivi" },
      { label: "Qoplama", value: "Ekologik nemis OSMO moyi" },
      { label: "Montaj", value: "Atelier ustalari tomonidan o'rnatiladi" },
    ],
  },
  {
    id: "tivoli",
    slug: "tivoli-bar-stuli",
    titleUz: "Tivoli Bar Stuli",
    titleRu: "Барный стул Tivoli",
    titleEn: "Tivoli Bar Stool",
    article: "PM-042",
    categorySlug: "kitchen",
    categoryName: "Oshxona",
    material: "Tabiiy eman",
    dimensions: "48 × 52 × 92 sm",
    warranty: "3 yil rasmiy kafolat",
    stockStatus: "IN_STOCK",
    descUz: "Tabiiy teri o'rindiq, patinatsiyalangan bronza oyoq tayanchi va me'moriy yengillik.",
    descRu: "Сиденье из натуральной кожи, подставка для ног из состаренной бронзы, легкость формы.",
    descEn: "Full-grain leather seat, antique bronze footrest, sculpted solid oak backrest.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDG5ms-kq1fJasZ0lWuPSUNkcRIFr-NC6tJyRf9BB5CZyZxCejbo-biKlkRKXvO6Hx5rwHAsQCjWOyCaUBV3_WnnZ1TXfLHOK8bDZvuKf7tCX2beMTUf198rKbzslfPPGVLIHntGk779vLSKamGZM9QDFp8LznBV4heziZGe8hSyjoCI1cf_0ROhGuR9SZqfDV9r_jzfxfv8nkNGxhKTEVcG7oaF6cbUeK5iSV-Cr5k5HSe-k1hZwlWWnAncw5kDygZoUwCz5PfKF8",
      "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "Konyak teri", hex: "#9E5630" },
      { name: "Qora teri", hex: "#22201F" },
    ],
    characteristics: [
      { label: "O'rindiq", value: "Italiya tabiiy anilin terisi" },
      { label: "Karkas", value: "Massiv qattiq eman" },
      { label: "O'rindiq balandligi", value: "68 sm (orol/bar peshtaxtasi uchun)" },
    ],
  },
  {
    id: "atelier-desk",
    slug: "atelier-ish-stoli",
    titleUz: "Atelier Ish Stoli",
    titleRu: "Письменный стол Atelier",
    titleEn: "Atelier Executive Desk",
    article: "PM-051",
    categorySlug: "office",
    categoryName: "Ish xonasi",
    material: "Yong'oq",
    dimensions: "180 × 80 × 76 sm",
    warranty: "5 yil rasmiy kafolat",
    stockStatus: "MADE_TO_ORDER",
    descUz: "Yashirin kabel kanallari, Amerika yong'og'i yuzasi va travertin bezak detali.",
    descRu: "Скрытые кабель-каналы, поверхность из массива ореха и изысканная деталь из травертина.",
    descEn: "Integrated cable management, solid American walnut worktop, inset travertine detail.",
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAbeZnQReuZQCp1ec_QXm0xCXCF82jU0GzTOKZCscOdC3kI4mjq2cdC4tOq5a3I9adnBoIVwsc9XOO7buf6KXoHtueyiyFxqXJemtCDAXmKc7UwJZDGSwdAH_Hb8qGOAMM3B571shjvyj6wEH2CAEesmgt120PjgYUWciYAINqhbDkW7_s3EComKsDguGvsHYF6OZzzfpblDrvXXiieFVTAl1OC_UV6ogAlFM4JNqkVeDt4mPcytvhQDgIRKaj4y07u4rWKlpuCE8k",
      "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: [
      { name: "To'q yong'oq", hex: "#4C382C" },
      { name: "Eman & Latun", hex: "#7E6A56" },
    ],
    characteristics: [
      { label: "Material", value: "Tabiiy qora yong'oq massivi" },
      { label: "Qo'shimcha", value: "Simsiz quvvatlagich va yashirin tortma" },
      { label: "Kafolat", value: "5 yil" },
    ],
  },
];
